apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "microflow.fullname" . }}-frontend-config
  labels:
    {{- include "microflow.labels" . | nindent 4 }}
data:
  VITE_USER_API_URL: {{ .Values.env.frontend.VITE_USER_API_URL | quote }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "microflow.fullname" . }}-user-config
  labels:
    {{- include "microflow.labels" . | nindent 4 }}
data:
  PORT: {{ .Values.env.user.PORT | quote }}