apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ include "microflow.fullname" . }}-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        {{- range .Values.ingress.hosts }}
        - {{ .host | quote }}
        {{- end }}
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "microflow.fullname" . }}-vs
spec:
  hosts:
    {{- range .Values.ingress.hosts }}
    - {{ .host | quote }}
    {{- end }}
  gateways:
    - {{ include "microflow.fullname" . }}-gateway
  http:
    - match:
        - uri:
            prefix: /api/user
      route:
        - destination:
            host: {{ include "microflow.fullname" . }}-user
            port:
              number: 4002
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: {{ include "microflow.fullname" . }}-frontend
            port:
              number: 80