apiVersion: v1
kind: Secret
metadata:
  name: {{ include "microflow.fullname" . }}-supabase
  labels:
    {{- include "microflow.labels" . | nindent 4 }}
type: Opaque
data:
  VITE_SUPABASE_URL: {{ .Values.env.frontend.VITE_SUPABASE_URL | b64enc | quote }}
  VITE_SUPABASE_ANON_KEY: {{ .Values.env.frontend.VITE_SUPABASE_ANON_KEY | b64enc | quote }}
  SUPABASE_URL: {{ .Values.env.user.SUPABASE_URL | b64enc | quote }}
  SUPABASE_ANON_KEY: {{ .Values.env.user.SUPABASE_ANON_KEY | b64enc | quote }}