apiVersion: v1
kind: Service
metadata:
  name: {{ include "microflow.fullname" . }}-user
  labels:
    {{- include "microflow.labels" . | nindent 4 }}
    app.kubernetes.io/component: user
spec:
  type: {{ .Values.service.user.type }}
  ports:
    - port: {{ .Values.service.user.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "microflow.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: user