# Global configuration
global:
  environment: production
  imageRegistry: ${ACR_NAME}.azurecr.io
  imagePullSecrets:
  - name: acr-auth-secret

# Frontend configuration
frontend:
  enabled: true
  replicaCount: 2
  image:
    repository: ${ACR_NAME}.azurecr.io/frontend
    tag: latest
    pullPolicy: Always
  imagePullSecrets:
  - name: acr-auth-secret
  service:
    type: LoadBalancer
    port: 80
    targetPort: 80
  resources:
    limits:
      cpu: "500m"
      memory: "512Mi"
    requests:
      cpu: "200m"
      memory: "256Mi"
  livenessProbe:
    enabled: true
    path: /health
    initialDelaySeconds: 30
    periodSeconds: 30
  env:
    VITE_API_URL: http://user-service:4002
    NODE_ENV: production

# User Service configuration
user:
  enabled: true
  replicaCount: 2
  image:
    repository: ${ACR_NAME}.azurecr.io/user-service
    tag: latest
  imagePullSecrets:
  - name: acr-auth-secret
  service:
    type: LoadBalancer
    port: 4002
    targetPort: 4002
  resources:
    limits:
      cpu: "500m"
      memory: "512Mi"
    requests:
      cpu: "200m"
      memory: "256Mi"
  livenessProbe:
    enabled: true
    path: /health
    initialDelaySeconds: 30
    periodSeconds: 30

# Metrics Service configuration
metrics:
  enabled: true
  replicaCount: 2
  image:
    repository: ${ACR_NAME}.azurecr.io/metrics-service
    tag: latest
  imagePullSecrets:
  - name: acr-auth-secret
  service:
    type: LoadBalancer
    port: 4003
    targetPort: 4003
  resources:
    limits:
      cpu: "500m"
      memory: "512Mi"
    requests:
      cpu: "200m"
      memory: "256Mi"
  livenessProbe:
    enabled: true
    path: /health
    initialDelaySeconds: 30
    periodSeconds: 30

# Analytics Service configuration
analytics:
  enabled: true
  replicaCount: 2
  image:
    repository: ${ACR_NAME}.azurecr.io/analytics-service
    tag: latest
  imagePullSecrets:
  - name: acr-auth-secret
  service:
    type: LoadBalancer
    port: 4004
    targetPort: 4004
  resources:
    limits:
      cpu: "500m"
      memory: "512Mi"
    requests:
      cpu: "200m"
      memory: "256Mi"
  livenessProbe:
    enabled: true
    path: /health
    initialDelaySeconds: 30
    periodSeconds: 30
