apiVersion: v1
kind: Service
metadata:
  name: metrics-service
  labels:
    app: metrics-service
spec:
  type: LoadBalancer
  ports:
  - port: 4003
    targetPort: 4003
    protocol: TCP
  selector:
    app: metrics-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: metrics-service
  namespace: sasso
spec:
  replicas: 2
  selector:
    matchLabels:
      app: metrics-service
  template:
    metadata:
      labels:
        app: metrics-service
    spec:
      containers:
      - name: metrics-service
        image: ${ACR_NAME}.azurecr.io/metrics-service:latest
        ports:
        - containerPort: 4003
        envFrom:
        - configMapRef:
            name: app-config
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        livenessProbe:
          httpGet:
            path: /health
            port: 4003
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /health
            port: 4003
          initialDelaySeconds: 5
          periodSeconds: 10
