apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: sasso-webflow
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: frontend
---
apiVersion: v1
kind: Service
metadata:
  name: analytics-service
  namespace: sasso-webflow
spec:
  type: ClusterIP
  ports:
  - port: 4001
    targetPort: 4001
  selector:
    app: analytics-service
---
apiVersion: v1
kind: Service
metadata:
  name: metrics-service
  namespace: sasso-webflow
spec:
  type: ClusterIP
  ports:
  - port: 4003
    targetPort: 4003
  selector:
    app: metrics-service
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: sasso-webflow
spec:
  type: ClusterIP
  ports:
  - port: 4002
    targetPort: 4002
  selector:
    app: user-service
