---
parameters:
  acrName: ''

stages:
- stage: Build
  displayName: 'Build and Push Images'
  dependsOn: ['CodeAnalysis', 'SecurityScan']
  jobs:
  - job: BuildImages
    steps:
    - task: Docker@2
      displayName: 'Build and push frontend'
      inputs:
        containerRegistry: '$(ACR_SERVICE_CONNECTION)'
        repository: '${{ parameters.acrName }}/frontend'
        command: 'buildAndPush'
        Dockerfile: 'frontend/Dockerfile'
        tags: |
          $(Build.BuildId)
          latest

    - task: Docker@2
      displayName: 'Build and push metrics service'
      inputs:
        containerRegistry: '$(ACR_SERVICE_CONNECTION)'
        repository: '${{ parameters.acrName }}/metrics-service'
        command: 'buildAndPush'
        Dockerfile: 'metrics-service/Dockerfile'
        tags: |
          $(Build.BuildId)
          latest

    - task: Docker@2
      displayName: 'Build and push user service'
      inputs:
        containerRegistry: '$(ACR_SERVICE_CONNECTION)'
        repository: '${{ parameters.acrName }}/user-service'
        command: 'buildAndPush'
        Dockerfile: 'user-service/Dockerfile'
        tags: |
          $(Build.BuildId)
          latest 