---
parameters:
  acrName: ''

stages:
- stage: Build
  displayName: 'Build and Push Images'
  dependsOn: CodeAnalysis
  jobs:
  - job: BuildImages
    steps:
    - checkout: self
      displayName: 'Checkout code'

    - task: Docker@2
      displayName: 'Build and push frontend'
      inputs:
        containerRegistry: 'ACR.sasso-webflow'
        repository: 'frontend'
        command: 'buildAndPush'
        Dockerfile: 'sasso-webflow-app/frontend/Dockerfile'
        context: 'sasso-webflow-app/frontend'
        tags: |
          $(Build.BuildId)
          latest

    - task: Docker@2
      displayName: 'Build and push analytics service'
      inputs:
        containerRegistry: 'ACR.sasso-webflow'
        repository: 'analytics-service'
        command: 'buildAndPush'
        Dockerfile: 'sasso-webflow-app/services/analytics/Dockerfile'
        context: 'sasso-webflow-app/services/analytics'
        tags: |
          $(Build.BuildId)
          latest

    - task: Docker@2
      displayName: 'Build and push metrics service'
      inputs:
        containerRegistry: 'ACR.sasso-webflow'
        repository: 'metrics-service'
        command: 'buildAndPush'
        Dockerfile: 'sasso-webflow-app/services/metrics/Dockerfile'
        context: 'sasso-webflow-app/services/metrics'
        tags: |
          $(Build.BuildId)
          latest

    - task: Docker@2
      displayName: 'Build and push user service'
      inputs:
        containerRegistry: 'ACR.sasso-webflow'
        repository: 'user-service'
        command: 'buildAndPush'
        Dockerfile: 'sasso-webflow-app/services/user/Dockerfile'
        context: 'sasso-webflow-app/services/user'
        tags: |
          $(Build.BuildId)
          latest 