---
parameters:
  acrName: ''

stages:
- stage: Build
  displayName: 'Build and Push Images'
  dependsOn: CodeAnalysis
  jobs:
  - job: BuildImages
    steps:
    - checkout: self
      displayName: 'Checkout code'
      path: 'sasso-webflow-app'

    - task: Docker@2
      displayName: 'Build and push frontend'
      inputs:
        containerRegistry: 'ACR.sasso-webflow'
        repository: 'frontend'
        command: 'buildAndPush'
        Dockerfile: 'frontend/Dockerfile'
        context: 'frontend'
        workingDirectory: '$(Build.SourcesDirectory)'
        buildContext: '$(Build.SourcesDirectory)/frontend'
        tags: |
          $(Build.BuildId)
          latest

    - task: Docker@2
      displayName: 'Build and push analytics service'
      inputs:
        containerRegistry: 'ACR.sasso-webflow'
        repository: 'analytics-service'
        command: 'buildAndPush'
        Dockerfile: 'services/analytics/Dockerfile'
        context: 'services/analytics'
        workingDirectory: '$(Build.SourcesDirectory)'
        buildContext: '$(Build.SourcesDirectory)/services/analytics'
        tags: |
          $(Build.BuildId)
          latest

    - task: Docker@2
      displayName: 'Build and push metrics service'
      inputs:
        containerRegistry: 'ACR.sasso-webflow'
        repository: 'metrics-service'
        command: 'buildAndPush'
        Dockerfile: 'services/metrics/Dockerfile'
        context: 'services/metrics'
        workingDirectory: '$(Build.SourcesDirectory)'
        buildContext: '$(Build.SourcesDirectory)/services/metrics'
        tags: |
          $(Build.BuildId)
          latest

    - task: Docker@2
      displayName: 'Build and push user service'
      inputs:
        containerRegistry: 'ACR.sasso-webflow'
        repository: 'user-service'
        command: 'buildAndPush'
        Dockerfile: 'services/user-management/Dockerfile'
        context: 'services/user-management'
        workingDirectory: '$(Build.SourcesDirectory)'
        buildContext: '$(Build.SourcesDirectory)/services/user-management'
        tags: |
          $(Build.BuildId)
          latest 