---
parameters:
  acrName: ''

stages:
- stage: Build
  displayName: 'Build and Push Images'
  dependsOn: CodeAnalysis
  jobs:
  - job: BuildImages
    steps:
    - task: Docker@2
      displayName: 'Build and push frontend'
      inputs:
        containerRegistry: 'ACR.sasso-webflow'
        repository: 'frontend'
        command: 'buildAndPush'
        Dockerfile: 'frontend/Dockerfile'
        tags: |
          $(Build.BuildId)
          latest

    - task: Docker@2
      displayName: 'Build and push analytics service'
      inputs:
        containerRegistry: 'ACR.sasso-webflow'
        repository: 'analytics-service'
        command: 'buildAndPush'
        Dockerfile: 'services/analytics/Dockerfile'
        tags: |
          $(Build.BuildId)
          latest

    - task: Docker@2
      displayName: 'Build and push metrics service'
      inputs:
        containerRegistry: 'ACR.sasso-webflow'
        repository: 'metrics-service'
        command: 'buildAndPush'
        Dockerfile: 'services/metrics/Dockerfile'
        tags: |
          $(Build.BuildId)
          latest

    - task: Docker@2
      displayName: 'Build and push user service'
      inputs:
        containerRegistry: 'ACR.sasso-webflow'
        repository: 'user-service'
        command: 'buildAndPush'
        Dockerfile: 'services/user/Dockerfile'
        tags: |
          $(Build.BuildId)
          latest 