---
parameters:
  acrName: ''

stages:
- stage: SecurityScan
  displayName: 'Security Scanning'
  jobs:
  - job: TrivyScan
    steps:
    - task: Docker@2
      inputs:
        command: 'login'
        containerRegistry: 'acr-connection'
        repository: '$(ACR_NAME).azurecr.io'
      displayName: 'Login to ACR'

    - script: |
        curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin v0.18.3
      displayName: 'Install Trivy'
    
    - script: |
        for service in frontend metrics-service user-service; do
          echo "Scanning $service Dockerfile"
          trivy config --severity HIGH,CRITICAL --exit-code 1 ./$service/Dockerfile || true
          
          echo "Scanning $service dependencies"
          trivy fs --severity HIGH,CRITICAL --exit-code 1 ./$service || true
        done
      displayName: 'Scan Dockerfiles and Dependencies'
      continueOnError: true

    - script: |
        # Scan for secrets
        trivy fs --security-checks secret .
      displayName: 'Scan for Secrets'
      continueOnError: true

    - script: |
        # Scan Docker images
        for service in sasso-user-service sasso-analytics-service sasso-metrics-service; do
          echo "Scanning $service image"
          trivy image $(ACR_NAME).azurecr.io/$service:$(Build.BuildId) --severity HIGH,CRITICAL --exit-code 1
        done
      displayName: 'Scan Docker Images'
      condition: succeededOrFailed() 