---
parameters:
  acrName: ''

stages:
- stage: SecurityScan
  displayName: 'Security Scanning'
  jobs:
  - job: TrivyScan
    steps:
    - task: Docker@2
      inputs:
        command: 'login'
        containerRegistry: 'ACR.sasso-webflow'
        repository: '$(ACR_NAME).azurecr.io'
      displayName: 'Login to ACR'

    - script: |
        curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin v0.18.3
      displayName: 'Install Trivy'
    
    - script: |
        for service in frontend metrics-service user-service; do
          echo "Scanning $service Dockerfile"
          trivy config --severity HIGH,CRITICAL --exit-code 1 ./$service/Dockerfile || true
          
          echo "Scanning $service dependencies"
          trivy fs --severity HIGH,CRITICAL --exit-code 1 ./$service || true
        done
      displayName: 'Scan Dockerfiles and Dependencies'
      continueOnError: true

    - script: |
        # Scan for secrets
        trivy fs --vuln-type secret .
      displayName: 'Scan for Secrets'
      continueOnError: true

    - script: |
        echo "Scanning user service image..."
        trivy image --severity HIGH,CRITICAL --exit-code 1 "$(ACR_NAME).azurecr.io/sasso-user-service:$(Build.BuildId)"
      displayName: 'Scan User Service Image'
      condition: succeededOrFailed()

    - script: |
        echo "Scanning analytics service image..."
        trivy image --severity HIGH,CRITICAL --exit-code 1 "$(ACR_NAME).azurecr.io/sasso-analytics-service:$(Build.BuildId)"
      displayName: 'Scan Analytics Service Image'
      condition: succeededOrFailed()

    - script: |
        echo "Scanning metrics service image..."
        trivy image --severity HIGH,CRITICAL --exit-code 1 "$(ACR_NAME).azurecr.io/sasso-metrics-service:$(Build.BuildId)"
      displayName: 'Scan Metrics Service Image'
      condition: succeededOrFailed() 