trigger:
  branches:
    include:
      - main
  paths:
    include:
      - 'sasso-webflow-app/**'
      - '.azure-pipelines/**'

variables:
  - group: AKS-Variables
  - name: DOCKER_BUILDKIT
    value: 1
  - name: NODE_VERSION
    value: '20.x'

stages:
  - stage: Build
    displayName: 'Build Frontend'
    jobs:
      - job: BuildFrontend
        displayName: 'Build and Push Frontend'
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: $(NODE_VERSION)
            displayName: 'Install Node.js'

          - script: |
              cd sasso-webflow-app/frontend
              npm install --legacy-peer-deps
              npm run build
            displayName: 'Build Frontend'

          - task: Docker@2
            displayName: 'Build and Push Frontend Image'
            inputs:
              containerRegistry: $(ACR_SERVICE_CONNECTION)
              repository: 'frontend'
              command: buildAndPush
              Dockerfile: sasso-webflow-app/frontend/Dockerfile
              tags: |
                $(Build.BuildId)
                latest
              buildContext: sasso-webflow-app/frontend

  - stage: Deploy
    displayName: 'Deploy to AKS'
    dependsOn: Build
    condition: succeeded()
    jobs:
      - job: Deploy
        displayName: 'Deploy to AKS'
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - task: HelmInstaller@1
            inputs:
              helmVersionToInstall: 'latest'

          - task: AzureCLI@2
            inputs:
              azureSubscription: $(AZURE_SUBSCRIPTION)
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                az aks get-credentials \
                  --resource-group $(RESOURCE_GROUP) \
                  --name $(AKS_CLUSTER_NAME)

          - task: HelmDeploy@0
            inputs:
              command: 'upgrade'
              chartType: 'FilePath'
              chartPath: './sasso-webflow-app/helm/microflow'
              releaseName: 'sasso-services'
              namespace: 'sasso-webflow'
              arguments: >
                --install 
                --create-namespace
                --set frontend.image.tag=$(Build.BuildId)
                --values ./sasso-webflow-app/helm/microflow/values.yaml 