trigger:
  branches:
    include:
      - main
  paths:
    include:
      - 'sasso-webflow-app/**'
      - '.azure-pipelines/**'

variables:
  - group: AKS-Variables
  - name: DOCKER_BUILDKIT
    value: 1

stages:
  - template: stages/code-analysis.yaml
    parameters:
      acrName: $(ACR_NAME)

  - template: stages/build.yaml
    parameters:
      acrName: $(ACR_NAME)

  - template: stages/deploy.yaml
    parameters:
      resourceGroup: 'sasso-dev-rg'
      aksCluster: 'sasso-dev-aks'
      acrName: $(ACR_NAME) 