trigger:
  branches:
    include:
      - main
      - develop
      - feature/*

pr:
  branches:
    include:
      - main
      - develop

variables:
  - template: variables/vars.yaml

pool:
  vmImage: 'ubuntu-latest'

stages:
- template: stages/code-analysis.yaml
  parameters:
    sonarProjectKey: $(SONAR_PROJECT_KEY)
    sonarOrganization: $(SONAR_ORGANIZATION)

- template: stages/security-scan.yaml
  parameters:
    acrName: $(ACR_NAME)

- template: stages/build.yaml
  parameters:
    acrName: $(ACR_NAME)

- template: stages/deploy.yaml
  parameters:
    resourceGroup: $(RESOURCE_GROUP)
    aksCluster: $(AKS_CLUSTER) 