trigger:
  branches:
    include:
    - main
  paths:
    include:
    - services/*
    - kubernetes/backend.yaml

variables:
  - group: azure-config
  - name: dockerRegistryServiceConnection
    value: 'your-acr-connection'
  - name: containerRegistry
    value: 'your-acr.azurecr.io'
  - name: imagePullSecret
    value: 'acr-secret'

extends:
  template: azure-pipelines-template.yml
  parameters:
    serviceName: 'backend'
    serviceDirectory: 'services'
    dockerfilePath: 'services/Dockerfile'
    sonarProjectKey: 'sasso-backend'
    sonarProjectName: 'Sasso Backend'