trigger:
  branches:
    include:
    - main
  paths:
    include:
    - frontend/*
    - kubernetes/frontend.yaml

variables:
  - group: azure-config
  - name: dockerRegistryServiceConnection
    value: 'your-acr-connection'
  - name: containerRegistry
    value: 'your-acr.azurecr.io'
  - name: imagePullSecret
    value: 'acr-secret'

extends:
  template: azure-pipelines-template.yml
  parameters:
    serviceName: 'frontend'
    serviceDirectory: 'frontend'
    dockerfilePath: 'frontend/Dockerfile'
    sonarProjectKey: 'sasso-frontend'
    sonarProjectName: 'Sasso Frontend'